Order routes #21
socialMediaRoyalty/socialMediaRoyalty pull request #48
Opened 2017-06-09 15:01 UTC by Nitiquita

2017-06-11 13:43 UTC, stella-yc requested changes
Thank you Nitiquita! I included some comments, give me a call if you want to talk it out!

2017-06-11 13:43 UTC, stella-yc commented on db/models/order.js
> +  // Order.hasMany(Product, {through: 'OrderDetail'})
remove comment

2017-06-11 13:43 UTC, stella-yc commented on server/auth.filters.js
> +    var err = new Error('not logged in')
remove, Allie is working on this

2017-06-11 13:43 UTC, stella-yc commented on server/orders.js
> +    if (req.user.isAdmin === true) {
just make it 
if (req.user.isAdmin)
for consistency

2017-06-11 13:43 UTC, stella-yc commented on server/orders.js
> +        })
Add a catch here!

2017-06-11 13:43 UTC, stella-yc commented on server/orders.js
> +    Order.findAll({
As it is, we would never reach this Order.findAll for req.query.
PERHAPS Use an if statement earlier checking if there is req.query, maybe.

2017-06-11 13:43 UTC, stella-yc commented on server/auth.filters.js
> +    next(err)
Is this a style thing? What is advantage of next vs throw?

2017-06-11 13:43 UTC, stella-yc commented on server/orders.js
> +    }).then(cart => Order.create({
Does this get to the Order.create line?
Also, you find the Cart, but how do we update the Order Detail model to include what used to be in Cart Detail?

2017-06-11 13:43 UTC, stella-yc commented on server/orders.js
> +  .param('oid', (req, res, next, oid) => {
When you look for an Order, consider including Product? That way we can see all the products within that order

2017-06-11 14:53 UTC, Nitiquita commented on server/auth.filters.js
> +    next(err)
I think next is better to use in express from what I'm looking at online, but we still need an error handler to deal with it.

2017-06-11 14:58 UTC, Nitiquita commented on server/orders.js
> +  .param('oid', (req, res, next, oid) => {
Good call! I'll add it.

2017-06-11 15:03 UTC, Nitiquita commented on server/orders.js
> +  .param('oid', (req, res, next, oid) => {
Unfortunately, they are not associated...

2017-06-11 18:27 UTC, Nitiquita commented
Notes: the difference between OrderDetail and order-details tables?

2017-06-11 21:10 UTC, stella-yc commented
Sorry I just saw this email!

Try deleting all the tables in your database, and then doing npm run dev
and then npm run seed. I have to keep doing this every time we change
models, since I don't think postico will delete old ones?

-Stella Chung



On Sun, Jun 11, 2017 at 2:27 PM, Nitika Nadgar <notifications@github.com>
wrote:

> Notes: the difference between OrderDetail and order-details tables?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/socialMediaRoyalty/socialMediaRoyalty/pull/48#issuecomment-307647456>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ARiJUPWUBU17WiDan_jNg4Ikyo6M4Ckxks5sDDGFgaJpZM4N1eHy>
> .
>

2017-06-11 22:50 UTC, stella-yc commented on server/auth.filters.js
> +    next(err)
cool!

2017-06-12 20:55 UTC, stella-yc approved these changes

2017-06-12 20:55 UTC, merged